name: CI - Code Quality

on:
  pull_request:
    branches: [main, dev]
    paths-ignore:
      - ".github/**"
      - "*.md"
      - "docs/**"

jobs:
  quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Check code formatting
        run: npm run format:check

      - name: Check TypeScript types
        run: npm run type-check

      - name: Build project
        run: npm run build

      - name: Run all quality checks
        run: npm run check-all

  build-success:
    name: Build Success Summary
    needs: quality
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Success notification
        run: |
          echo "✅ All quality checks passed!"
          echo "✅ Linting: Passed"
          echo "✅ Formatting: Passed" 
          echo "✅ TypeScript: Passed"
          echo "✅ Build: Passed"
